### PR TITLE
Allow lists to contain non-comparable elements

### PR DESCRIPTION
**Pull request by BarrensZeppelin**
The current design uses comparability of elements only to detect vacant entries in leaf node children lists, using the zero value of the element type as "vacant".
The reason we care about vacant entries is to avoid copy operations in certain Slice calls. If the entries are not vacant, we have to "zero" the entries in the returned slice to remove references to allocated memory.
Therefore, (hackily) treating the zero value as vacant works because the zero value for pointers is nil (it does not reference anything). However, requiring the list elements to be comparable is inconvenient. There shouldn't be a type bound on the elements of a general purpose list.

With this change vacancy is kept track of with a bitset in list leaf nodes.

### CODE REVIEW

**Comment by BarrensZeppelin** [comment]
@benbjohnson There are at least two alternate ways of implementing this, if you don't like the implementation complexity of the bitsets.

1. The no-copy optimisation for slices can simply be removed such that we always have to copy some list nodes and zero them appropriately when making a slice.
2. We can more explicitly store which entries are vacant, e.g. with an array of booleans in each list leaf. I assume this will require a bit more space, but it might make the implementation more obvious.

**Comment by benbjohnson** [comment]
hey @BarrensZeppelin, sorry for the delay. I haven't had much time to focus on `immutable` lately and I'm not super familiar with the ins-and-outs of generics. If anyone else from the community has time to review this and give feedback, I'd appreciate it.

**Comment by BarrensZeppelin** [comment]
@laher

**Review by laher — APPROVED** [review]
The change to `any` looks good to me. You're right it's better not to restrict the types allowed in a list.

I get the approach in theory, it sounds legit to me.  I'm not the right person to assess the bit-flipping, but the tests still pass and you added a specific test which tests the change so... 👍 IMO

**Comment by benbjohnson** [comment]
Thanks everybody! 🙏

**Pull request merged**
