### PR TITLE
Support a hasher and comparer for uint arrays

### PR DESCRIPTION
**Pull request by guenhter**

### CODE REVIEW

**Comment by benbjohnson** [comment]
Sorry for the really slow response, @guenhter. This seems overly specific and I'm not sure how often people will use uint arrays for keys so I'm closing this. Folks can copy the hasher/comparer here if they need it.

**Comment by guenhter** [comment]
The main reason I added this (as far as I can remember) was to support UUID which are under the hood byte arrays. 
This is quite useful I think.

**Comment by guenhter** [comment]
See

https://github.com/google/uuid/blob/44b5fee7c49cf3bcdf723f106b36d56ef13ccc88/uuid.go#L20

**Comment by benbjohnson** [comment]
@guenhter That's a good point. That is useful for UUIDs. I'm hesitant to use a comparer with `reflect` calls in the `Compare()` function though. Some folks recently added generics support into `immutable`. I'd be open to a generic implementation instead.

**Comment by guenhter** [comment]
A generics solution sounds pretty nice to me.

**Pull request closed without merging**
